version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "next"
        versions: ["<14.0.0"]
