app = "mcp-citybites"
primary_region = "fra"

[build]
  dockerfile = "mcp-citybites/Dockerfile"
  context = ".."

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
