name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: npm
          cache-dependency-path: |
            apps/agent/package-lock.json
            apps/mcp-citybites/package-lock.json

      - name: Install dependencies (agent)
        run: npm ci
        working-directory: apps/agent

      - name: Install dependencies (MCP)
        run: npm ci
        working-directory: apps/mcp-citybites
        env:
          SKIP_PLAYWRIGHT_INSTALL: "true"
          PW_SKIP_BROWSER_DOWNLOAD: "1"
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
          DISABLE_PDF: "true"

      - name: Validate agent build
        run: npm run build
        working-directory: apps/agent

      - name: Validate MCP build
        run: npm run build
        working-directory: apps/mcp-citybites
        env:
          SKIP_PLAYWRIGHT_INSTALL: "true"
          PW_SKIP_BROWSER_DOWNLOAD: "1"
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
          DISABLE_PDF: "true"

  deploy-fly:
    needs: test
    runs-on: ubuntu-latest
# Fly.io deployment will proceed with token
    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Verify Fly CLI installation
        run: |
          which flyctl || which fly || echo "Flyctl not found"
          flyctl version || fly version || echo "Cannot get version"

      - name: Deploy agent service
        run: flyctl deploy --config apps/agent/fly.toml --dockerfile apps/agent/Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy MCP service
        run: flyctl deploy --remote-only
        working-directory: apps/mcp-citybites
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend:
    needs: deploy-fly
    runs-on: ubuntu-latest
# Vercel deployment enabled with correct ORG_ID and PROJECT_ID

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel environment (repo root)
        run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy Next.js frontend to Vercel (repo root)
        run: vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
